# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dc1194abd7133f5ab978d383b6a07b360be31391b1a241d4221b028062bc1a1c481916c844ee99de5d632439370b2b04da3c68734a5e9c31f0e572ae7cd84fd

test:
  secret_key_base: 7387328ef76ec77a7c50cbe8a367eb5d459a83fe274ce15d565b37427def191f22ec890e3d8ad199e4cab86c1c6d5eb1d4c4da09c35b740a00f91c0d413e708b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
